In [1]:
#txt-Datei einlesen

import numpy as np

def read_bingo_txt(file_path):
    file = open(file_path, 'r')
    
    first_line = file.readline()
    stripped_line = first_line.strip()
    splitted_line = first_line.split(',')
    splitted_int_line = [int(i) for i in splitted_line]
    bingo_draws = splitted_int_line
    
    Lines = file.readlines()
    bingo_fields = []
    bingo_field = []
    for line in Lines:
        if(line!="\n"):
            stripped_line = line.strip()
            splitted_line = line.split()
            splitted_int_line = [int(i) for i in splitted_line]
            bingo_field.append(splitted_int_line)
        else:
            bingo_fields.append(np.array(bingo_field))
            bingo_field.clear()
    
    return bingo_draws, bingo_fields[1:]

In [30]:
# Aufgabe 1

def cross_element_on_bingo_field(bingo_field, element):
    new_field = np.where(bingo_field == element, -1, bingo_field)
    return new_field

def check_if_bingo_field_wins(bingo_field):
        row_sums = bingo_field.sum(axis=1)
        col_sums = bingo_field.sum(axis=0)
        if(np.isin(-5, row_sums) or np.isin(-5, col_sums)):
            print("WINNER")
            print(bingo_field)
            return True
        else:
            return False

def play_bingo(bingo_draws, bingo_fields):
    for draw in bingo_draws:
        print("_____________")
        print(f"DRAW: {draw}")
        
        new_fields = []
        for bingo_field in bingo_fields:
            bingo_field = cross_element_on_bingo_field(bingo_field, draw)
            new_fields.append(bingo_field)
            
            #print(f"Bingo Field:")
            #print(bingo_field)
            #print("")
            
            if(check_if_bingo_field_wins(bingo_field)):
                break
        bingo_fields = new_fields
    return bingo_fields
        
        
bingo_draws, bingo_fields = read_bingo_txt("bingo.txt")
final_bingo_fields = play_bingo(bingo_draws, bingo_fields)
print(final_bingo_fields[0])
print("")
print(final_bingo_fields[1])
print("")
print(final_bingo_fields[2])
print("")

_____________
DRAW: 4
_____________
DRAW: 75
_____________
DRAW: 74
_____________
DRAW: 31
_____________
DRAW: 76
_____________
DRAW: 79
_____________
DRAW: 27
_____________
DRAW: 19
_____________
DRAW: 69
_____________
DRAW: 46
_____________
DRAW: 98
_____________
DRAW: 59
_____________
DRAW: 83
_____________
DRAW: 23
_____________
DRAW: 90
_____________
DRAW: 52
_____________
DRAW: 87
_____________
DRAW: 6
_____________
DRAW: 11
_____________
DRAW: 92
_____________
DRAW: 80
_____________
DRAW: 51
WINNER
[[-1 18 -1 35 55]
 [-1 85 -1 56 82]
 [-1 26 24 29 43]
 [-1 -1 -1 45 13]
 [-1 12 99 94 47]]
_____________
DRAW: 43
WINNER
[[-1 18 -1 35 55]
 [-1 85 -1 56 82]
 [-1 26 24 29 -1]
 [-1 -1 -1 45 13]
 [-1 12 99 94 47]]
_____________
DRAW: 5
WINNER
[[-1 18 -1 35 55]
 [-1 85 -1 56 82]
 [-1 26 24 29 -1]
 [-1 -1 -1 45 13]
 [-1 12 99 94 47]]
_____________
DRAW: 94
WINNER
[[-1 18 -1 35 55]
 [-1 85 -1 56 82]
 [-1 26 24 29 -1]
 [-1 -1 -1 45 13]
 [-1 12 99 -1 47]]
_____________
DRAW: 17
WINNER
[[-1 1

IndexError: list index out of range

In [11]:
# Aufgabe 2

def cross_element_on_bingo_field(bingo_field, element):
    new_field = np.where(bingo_field == element, -1, bingo_field)
    return new_field

def check_if_bingo_field_wins(bingo_field):
        row_sums = bingo_field.sum(axis=1)
        col_sums = bingo_field.sum(axis=0)
        if(np.isin(-5, row_sums) or np.isin(-5, col_sums)):
            return True
        else:
            return False

def play_bingo(bingo_draws, bingo_fields):
    for draw in bingo_draws:
        print("_____________")
        print(f"DRAW: {draw}")
        
        new_fields = []
        for bingo_field in bingo_fields:
            bingo_field = cross_element_on_bingo_field(bingo_field, draw)
            
            
            #print(f"Bingo Field:")
            #print(bingo_field)
            #print("")
            
            if(check_if_bingo_field_wins(bingo_field)):
                pass
            else:
                new_fields.append(bingo_field)
        bingo_fields = new_fields
        if len(new_fields) == 1:
            print("FINAL")
            print(new_fields[0])
            break
    return bingo_fields
        
        
bingo_draws, bingo_fields = read_bingo_txt("bingo.txt")
final_bingo_field = play_bingo(bingo_draws, bingo_fields)


_____________
DRAW: 4
_____________
DRAW: 75
_____________
DRAW: 74
_____________
DRAW: 31
_____________
DRAW: 76
_____________
DRAW: 79
_____________
DRAW: 27
_____________
DRAW: 19
_____________
DRAW: 69
_____________
DRAW: 46
_____________
DRAW: 98
_____________
DRAW: 59
_____________
DRAW: 83
_____________
DRAW: 23
_____________
DRAW: 90
_____________
DRAW: 52
_____________
DRAW: 87
_____________
DRAW: 6
_____________
DRAW: 11
_____________
DRAW: 92
_____________
DRAW: 80
_____________
DRAW: 51
_____________
DRAW: 43
_____________
DRAW: 5
_____________
DRAW: 94
_____________
DRAW: 17
_____________
DRAW: 15
_____________
DRAW: 67
_____________
DRAW: 25
_____________
DRAW: 30
_____________
DRAW: 48
_____________
DRAW: 47
_____________
DRAW: 62
_____________
DRAW: 71
_____________
DRAW: 85
_____________
DRAW: 58
_____________
DRAW: 60
_____________
DRAW: 1
_____________
DRAW: 72
_____________
DRAW: 99
_____________
DRAW: 3
_____________
DRAW: 35
_____________
DRAW: 42
_____________
DR